export const LIMITS = {
  CATEGORIES_LIMITS: 15,
  PRODUCTS_LIMITS: 20,
  RELATED_PRODUCTS_LIMITS: 20,
  BEST_SELLER_PRODUCTS_LIMITS: 12,
  POPULAR_PRODUCTS_LIMITS: 14,
  POPULAR_PRODUCTS_TWO_LIMITS: 7,
  ELETRONIC_PRODUCTS_LIMITS: 12,
  FASHION_PRODUCTS_LIMITS: 6,
  NEW_ARRIVAL_PRODUCTS_LIMITS: 12,
  LATEST_BLOG_LIMITS: 8,
};
